# Generated by Django 4.2.1 on 2023-05-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_tag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='is_main',
            field=models.BooleanField(null=True, verbose_name='Основной'),
        ),
    ]
